# typed: strict
# frozen_string_literal: true

require 'rubocop'
require 'sorbet-runtime'

# Top-level RuboCop namespace.
module RuboCop
  # Root namespace for RuboCop community and custom cops.
  module Cop
    # Custom cops targeting issues injected by Artificial Intelligence models.
    module AI
      # This cop checks for comments that contain an excessive sequence of adverbs
      # or seemingly random words, which are often generated by malfunctioning AI
      # tools or LLM doc generators.
      #
      # @example
      #   # bad
      #   # @param c_m [String] securely accurately dynamically visually intuitively conditionally ...
      #
      #   # good
      #   # @param c_m [String] the properly formatted parameter
      class AdverbSpam < ::RuboCop::Cop::Base
        extend T::Sig
        extend ::RuboCop::Cop::AutoCorrector

        # Detailed explanation of what the cop expects to find and correct when triggered.
        MSG = T.let('Avoid AI-generated spam inside comments (excessive adverbs/meaningless words).', String)

        # Triggered for each new file/investigation to scan comments for invalid documentation spam.
        #
        # @return [void]
        sig { void }
        def on_new_investigation
          # Pattern to match sequences of 2 or more words ending in 'ly'
          # including optional spaces and punctuation in between (but NOT newlines).
          pattern = T.let(/(?:[ \t]*\b[a-zA-Z]+ly\b[ \t,.]*){2,}/i, Regexp)

          processed_source.comments.each do |comment|
            text = comment.text
            next unless text.match?(pattern)

            add_offense(comment) do |corrector|
              new_text = text.gsub(pattern, '').rstrip
              # Ensure the comment still starts with '#' if it got stripped entirely
              new_text = '#' if new_text.empty?
              corrector.replace(comment, new_text)
            end
          end
        end
      end
    end
  end
end
