plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
require:
  - rubocop-thread_safety
  - rubocop-md

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'sorbet/**/*'
    - 'tmp/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true

RSpec/Dialect:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

Naming/VariableNumber:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 165

Naming/FileName:
  Exclude:
    - 'lib/rubocop-ai.rb'
    - '**/*.md'

ThreadSafety/DirChdir:
  Exclude:
    - 'rubocop-ai.gemspec'

Gemspec/DevelopmentDependencies:
  Enabled: false

# We need to enforce our own cop internally, but usually RuboCop extensions
# don't test themselves against their own cops. We can include it manually if needed.
